# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Publish

on: workflow_dispatch

jobs:
  publish:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout main branch & Change path to client 
      uses: actions/checkout@v2
      with: 
        ref: 'main'
        path: 'client'
    - name: Set Java Env
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish package
      run: mvn deploy 
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWD }}
